spring:
  application:
    name: Citronix
  datasource:
    url: jdbc:postgresql://localhost:5432/citronix
    username: soufiane
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
logging:
  level:
    root: INFO
    org.hibernate.validator: DEBUG
    org.springframework: WARN


##---------- API information ---------------------------------
contact:
  email: yc.ma

local-server:
  url: http://localhost:8080/

prod-server:
  url: http://localhost:8080/

project:
  version: 1.0
  title: Citornix
  description: Citornix pour la gestion des fermes
